# Generated by Django 3.1.5 on 2021-01-31 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('search_word', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ChildPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=255)),
                ('media', models.CharField(max_length=255)),
                ('page_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website_Indexer_App.parentpage')),
            ],
        ),
    ]
