# Generated by Django 3.1.5 on 2021-01-31 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website_Indexer_App', '0003_auto_20210131_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentpage',
            name='parent_url',
        ),
    ]
